version: '3'
services:

  app:
    build: .
    container_name: app_quiz
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/quiz
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=3003
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: 3003
      POSTGRES_DB: quiz
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  db-data:
